[uwsgi]
master          = true
die-on-term     = true

stats           = 127.0.0.1:8010
stats-http      = true

module          = project.wsgi:application
processes       = 2
touch-reload    = reload

disable-logging = true

max-requests    = 50000
enable-threads  = True
harakiri        = 60
buffer-size     = 16384
reload-mercy    = 30
need-app        = True

; ignore close errors
ignore-sigpipe
ignore-write-errors
disable-write-exception
